services:
  db:
    image: postgres:13.2-alpine
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"